language: objective-c
matrix:
  include:
    - osx_image: xcode12.0
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (4th generation),OS=14.0"'
    - osx_image: xcode12.0
      env: SIMULATOR="name=iPhone 11 Pro Max,OS=14.0"
    - osx_image: xcode11.5
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (4th generation),OS=13.5"'
    - osx_image: xcode11.5
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (3rd generation),OS=12.4"'
    - osx_image: xcode11.5
      env: 'SIMULATOR="name=iPhone SE,OS=11.2"'
    - osx_image: xcode11.5
      env: 'SIMULATOR="name=iPhone 7 Plus,OS=10.3.1"'
    - osx_image: xcode11.5
      env: 'SIMULATOR="name=iPad (5th generation),OS=10.3.1"'

before_install:
  - xcrun simctl list
  - brew update || brew update
  - gem install bundler
install:
  - if [ -z "$(brew ls --versions coreutils)" ] ; then brew install coreutils ; fi
  - gem install xcpretty --no-document --quiet
script:
  - ./scripts/ci.sh "${SIMULATOR}"
